In [ ]:
import torch
vector=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=True)
vector.shape,vector.device, vector.dtype

(torch.Size([2, 2]), device(type='cpu'), torch.int64)

In [ ]:
'''
1.	Illustrate the functions for Reshaping, viewing, stacking, squeezing and unsqueezing of tensors
'''
import torch

print(torch.__version__)

a=torch.tensor([1,2,3,4,5,6])
print("a:",a)

print("RESHAPING")

b=a.reshape(3,2)
print("b Reshaped Tensor:",b)

b1=b.t()
print("Transpose of b:",b1)

print("VIEWING")
#c=b1.view(3,2) error as b1 is of size (2,3)

c=b1.reshape(3,2).view(3,2) #this works
print("c View of Tensor:",c)

print("STACKING")

s1=torch.tensor([1,2,3])
s2=torch.tensor([4,5,6])
s3=torch.stack((s1,s2),dim=1)
print("\ns3 stack along col:",s3)

s4=torch.stack((s1,s2),dim=0)
print("\ns4 stack along row:",s4)

s11=torch.tensor([[1,2,3],[4,5,6]])
s12=torch.tensor([[7,8,9],[10,11,12]])
s22=torch.stack((s11,s12),dim=0)
print("s22:",s22)

s11=torch.stack((s11,s12),dim=1)
print("s11:",s11)

print("SQUEEZING AND UNSQUEEZING")
#bracket order in indexwise-0,1,2,3

# UNSQUEEZE-adds extra brackets in whichever dim mentioned
y=torch.tensor([[[10,20,30],[40,50,60]],[[11,12,13],[14,15,16]]])
print(y)

y0=y.unsqueeze(0)
print(y0)

y1=y.unsqueeze(1)
print(y1)

y2=y.unsqueeze(2)
print(y2)

# SQUEEZE-removes the extra brackets in whichver dim mentioned
z=torch.tensor([[[[10,20,30],[40,50,60]],[[11,12,13],[14,15,16]]]])
print("\nz:",z)

z0=z.squeeze(0)
print(z0)

z=torch.tensor([[[[10,20,30],[40,50,60]]],[[[11,12,13],[14,15,16]]]])
print("\nz:",z)

z1=z.squeeze(1)
print(z1)

z=torch.tensor([[[[10,20,30]],[[40,50,60]]],[[[11,12,13]],[[14,15,16]]]])
print("\nz:",z)

z2=z.squeeze(2)
print(z2)


2.7.0+cpu
a: tensor([1, 2, 3, 4, 5, 6])
RESHAPING
b Reshaped Tensor: tensor([[1, 2],
        [3, 4],
        [5, 6]])
Transpose of b: tensor([[1, 3, 5],
        [2, 4, 6]])
VIEWING
c View of Tensor: tensor([[1, 3],
        [5, 2],
        [4, 6]])
STACKING

s3 stack along col: tensor([[1, 4],
        [2, 5],
        [3, 6]])

s4 stack along row: tensor([[1, 2, 3],
        [4, 5, 6]])
s22: tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
s11: tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])
SQUEEZING AND UNSQUEEZING
tensor([[[10, 20, 30],
         [40, 50, 60]],

        [[11, 12, 13],
         [14, 15, 16]]])
tensor([[[[10, 20, 30],
          [40, 50, 60]],

         [[11, 12, 13],
          [14, 15, 16]]]])
tensor([[[[10, 20, 30],
          [40, 50, 60]]],


        [[[11, 12, 13],
          [14, 15, 16]]]])
tensor([[[[10, 20, 30]],

         [[40, 50, 60]]],


        [[[11, 12, 13]],

     

In [ ]:
'''
2.	Illustrate the use of torch.permute().
'''

import torch

# Create a tensor
a = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Original tensor:\n", a)
#old dimension is (0,1,2)-->shape (2,2,3)

# new dimension will be (2,0,1)-->shape (3,2,2)
permuted = a.permute(2, 0, 1)
print("Permuted tensor:\n", permuted)

Original tensor:
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Permuted tensor:
 tensor([[[ 1,  4],
         [ 7, 10]],

        [[ 2,  5],
         [ 8, 11]],

        [[ 3,  6],
         [ 9, 12]]])


In [ ]:
'''
3.	Illustrate indexing in tensors'''

import torch

# Create a tensor
a = torch.tensor([1, 2, 3, 4, 5, 6])
print("Original tensor:", a)

print("Indexing with integers:")
print("a[0]:", a[0])

print("\nIndexing with slices:")
print("a[1:4]:", a[1:4])

print("\nIndexing with negative indices:")
print("a[-1]:", a[-1])

x=torch.tensor([[10,20,30],
                [40,50,60]])
print("single ele:",x[1,0]) #second row, first col ele
print("entire row:",x[0]) #first row
print("entire col:",x[:,0]) #all rows, first col

x1=x[0:2,0:2]
print(x1)

Original tensor: tensor([1, 2, 3, 4, 5, 6])
Indexing with integers:
a[0]: tensor(1)

Indexing with slices:
a[1:4]: tensor([2, 3, 4])
a[:3]: tensor([1, 2, 3])

Indexing with negative indices:
a[-1]: tensor(6)
single ele: tensor(40)
entire row: tensor([10, 20, 30])
entire col: tensor([10, 40])
tensor([[10, 20],
        [40, 50]])


In [33]:
'''
4.	Show how numpy arrays are converted to tensors and back again to numpy arrays
'''

import torch
import numpy as np

tensor=torch.tensor([[1,2,3],
                     [4,5,6]])

print("Tensor:",tensor,type(tensor))

np_arr=np.array(tensor)
print("Numpy arr:",np_arr,type(np_arr))

from_np=torch.from_numpy(np_arr)
print("Tensor from numpy:",from_np,type(from_np))

np_arr[0,0]=100
print("Change in np arr:",np_arr)
print("Change in tensor:",from_np) #change gets reflected in tensor

from_ten=tensor.numpy()
tensor[1,1]=100
print("\nChange in tensor:",tensor)
print("Change in np arr:",from_ten)#change gets reflected in tensor

copy_from_ten=tensor.numpy().copy()
tensor[1,2]=50
print("\nChange in tensor:",tensor)
print("Change in np arr:",copy_from_ten)#change DOES NOT reflected in tensor

np_2=np.array([1,2,3,4])
ten_np=torch.tensor(np_2)
np_2[0]=100
print("\nChange in np arr:",np_2)
print("Change in tensor:",ten_np)#change DOES NOT reflected in tensor

Tensor: tensor([[1, 2, 3],
        [4, 5, 6]]) <class 'torch.Tensor'>
Numpy arr: [[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
Tensor from numpy: tensor([[1, 2, 3],
        [4, 5, 6]]) <class 'torch.Tensor'>
Change in np arr: [[100   2   3]
 [  4   5   6]]
Change in tensor: tensor([[100,   2,   3],
        [  4,   5,   6]])

Change in tensor: tensor([[  1,   2,   3],
        [  4, 100,   6]])
Change in np arr: [[  1   2   3]
 [  4 100   6]]

Change in tensor: tensor([[  1,   2,   3],
        [  4, 100,  50]])
Change in np arr: [[  1   2   3]
 [  4 100   6]]

Change in np arr: [100   2   3   4]
Change in tensor: tensor([1, 2, 3, 4], dtype=torch.int32)


In [6]:
'''
5.	Create a random tensor with shape (7, 7).
'''

import torch

a=torch.rand(7,7)
print("Random Tensor of shape (7,7):",a)

Random Tensor of shape (7,7): tensor([[0.3008, 0.6906, 0.8944, 0.3930, 0.8690, 0.2852, 0.4131],
        [0.1796, 0.6215, 0.4840, 0.8838, 0.6771, 0.5074, 0.5671],
        [0.5630, 0.7798, 0.5960, 0.0631, 0.2119, 0.2776, 0.3629],
        [0.1428, 0.1657, 0.4212, 0.7518, 0.9241, 0.6684, 0.2507],
        [0.1919, 0.5225, 0.3258, 0.3260, 0.8501, 0.7168, 0.2944],
        [0.3489, 0.2531, 0.9075, 0.5055, 0.5257, 0.0534, 0.2603],
        [0.9537, 0.8289, 0.4572, 0.8231, 0.9390, 0.3093, 0.1707]])


In [ ]:
'''
6.	Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) 
(hint: you may have to transpose the second tensor).
'''
import torch

tensor = torch.rand((7, 7))
print('a:\n', tensor)

randomTensor = torch.rand(size=(1, 7))
print('\nb:\n', randomTensor)

randomTensor=randomTensor.t()

result=torch.matmul(tensor,randomTensor)
print("\nResult",result)

a:
 tensor([[0.9485, 0.7191, 0.5226, 0.3802, 0.5297, 0.3982, 0.2967],
        [0.5358, 0.5731, 0.9285, 0.5740, 0.5489, 0.5925, 0.0470],
        [0.0951, 0.6853, 0.0382, 0.4487, 0.1708, 0.2816, 0.3553],
        [0.0034, 0.9581, 0.7597, 0.2238, 0.3236, 0.1779, 0.6243],
        [0.5888, 0.5367, 0.9820, 0.5689, 0.2278, 0.8888, 0.3801],
        [0.4514, 0.8983, 0.2592, 0.3469, 0.0183, 0.3087, 0.4552],
        [0.9080, 0.4127, 0.4124, 0.4613, 0.3459, 0.5524, 0.8437]])

b:
 tensor([[0.7738, 0.5532, 0.6896, 0.7505, 0.6400, 0.6865, 0.9876]])
Result tensor([[2.6830],
        [2.6072],
        [1.4693],
        [2.1702],
        [2.9880],
        [1.9586],
        [2.9954]])


In [34]:
'''
7.	Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). '''

import torch
tensor_cpu1=torch.rand((2,3))
tensor_cpu2=torch.rand((2,3))

print(tensor_cpu1)
print(tensor_cpu1.device)

tensor_gpu1=tensor_cpu1.to('cuda')
tensor_gpu2=tensor_cpu2.to('cuda')

print(tensor_gpu1)
print(tensor_gpu1.device)

tensor([[0.8549, 0.5509, 0.2868],
        [0.2063, 0.4451, 0.3593]])
cpu


AssertionError: Torch not compiled with CUDA enabled

In [26]:
'''
8.	Perform a matrix multiplication on the tensors you created in 6 
(again, you may have to adjust the shapes of one of the tensors).'''

import torch
print("Q6 matrix",result.shape)
new=torch.matmul(result,result.t())
print("Result of matmul:",new)

Q6 matrix torch.Size([7, 1])
Result of matmul: tensor([[7.1983, 6.9949, 3.9421, 5.8225, 8.0166, 5.2547, 8.0364],
        [6.9949, 6.7973, 3.8307, 5.6580, 7.7901, 5.1063, 7.8094],
        [3.9421, 3.8307, 2.1589, 3.1887, 4.3902, 2.8777, 4.4011],
        [5.8225, 5.6580, 3.1887, 4.7097, 6.4844, 4.2504, 6.5005],
        [8.0166, 7.7901, 4.3902, 6.4844, 8.9279, 5.8521, 8.9500],
        [5.2547, 5.1063, 2.8777, 4.2504, 5.8521, 3.8360, 5.8666],
        [8.0364, 7.8094, 4.4011, 6.5005, 8.9500, 5.8666, 8.9722]])


In [28]:
'''
9.	Find the maximum and minimum values of the output of 7.'''

import torch
tensor1=torch.rand((2,3))
print(tensor1)

print("Max Value:",torch.max(tensor1))
print("Min value:",torch.min(tensor1))

tensor([[0.7391, 0.0838, 0.3576],
        [0.4792, 0.3144, 0.3312]])
Max Value: tensor(0.7391)
Min value: tensor(0.0838)


In [ ]:
'''
10.	Find the maximum and minimum index values of the output of 7.'''

import torch
tensor2=torch.rand((2,3))
print(tensor2)

#[0.12, 0.98, 0.45, 0.76, 0.05, 0.33]
#  0     1     2     3     4     5
print("Max Index Value:",torch.argmax(tensor2))
print("Min Index Value:",torch.argmin(tensor2))

tensor([[0.7267, 0.6663, 0.6618],
        [0.3464, 0.2958, 0.5332]])
Max Index Value: tensor(0)
Min Index Value: tensor(4)


In [4]:
'''
11.	Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 
dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it 
and print out the first tensor and it's shape as well as the second tensor and it's shape.
'''
import torch

torch.manual_seed(7)
tensor1=torch.rand(1,1,1,10)

print("Original tensor:",tensor1,tensor1.shape)

squeeze_ten=tensor1.squeeze()
print("\nSqueezed tensor:",squeeze_ten,squeeze_ten.shape)

Original tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

Squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
